// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/greeter/greeter.proto

package protoc_gen_kit_git

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cc58d5671cc8265, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cc58d5671cc8265, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GoodbyeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodbyeRequest) Reset()         { *m = GoodbyeRequest{} }
func (m *GoodbyeRequest) String() string { return proto.CompactTextString(m) }
func (*GoodbyeRequest) ProtoMessage()    {}
func (*GoodbyeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cc58d5671cc8265, []int{2}
}

func (m *GoodbyeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodbyeRequest.Unmarshal(m, b)
}
func (m *GoodbyeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodbyeRequest.Marshal(b, m, deterministic)
}
func (m *GoodbyeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodbyeRequest.Merge(m, src)
}
func (m *GoodbyeRequest) XXX_Size() int {
	return xxx_messageInfo_GoodbyeRequest.Size(m)
}
func (m *GoodbyeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodbyeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoodbyeRequest proto.InternalMessageInfo

func (m *GoodbyeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GoodbyeResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodbyeResponse) Reset()         { *m = GoodbyeResponse{} }
func (m *GoodbyeResponse) String() string { return proto.CompactTextString(m) }
func (*GoodbyeResponse) ProtoMessage()    {}
func (*GoodbyeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cc58d5671cc8265, []int{3}
}

func (m *GoodbyeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodbyeResponse.Unmarshal(m, b)
}
func (m *GoodbyeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodbyeResponse.Marshal(b, m, deterministic)
}
func (m *GoodbyeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodbyeResponse.Merge(m, src)
}
func (m *GoodbyeResponse) XXX_Size() int {
	return xxx_messageInfo_GoodbyeResponse.Size(m)
}
func (m *GoodbyeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodbyeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoodbyeResponse proto.InternalMessageInfo

func (m *GoodbyeResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "greetergrpc.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "greetergrpc.HelloResponse")
	proto.RegisterType((*GoodbyeRequest)(nil), "greetergrpc.GoodbyeRequest")
	proto.RegisterType((*GoodbyeResponse)(nil), "greetergrpc.GoodbyeResponse")
}

func init() { proto.RegisterFile("examples/greeter/greeter.proto", fileDescriptor_3cc58d5671cc8265) }

var fileDescriptor_3cc58d5671cc8265 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xcb, 0x4a, 0xc5, 0x30,
	0x10, 0x86, 0x2d, 0x5e, 0x0e, 0x8e, 0x57, 0x66, 0xa5, 0x55, 0x44, 0xa3, 0x0b, 0x45, 0x4e, 0x0a,
	0xfa, 0x02, 0xe2, 0xc2, 0xe3, 0xba, 0x4b, 0x77, 0x6d, 0x1d, 0x62, 0x69, 0x73, 0x31, 0x49, 0x41,
	0x9f, 0xc3, 0x17, 0x16, 0xd3, 0x54, 0x5a, 0xa8, 0xae, 0x32, 0xc9, 0xfc, 0x7c, 0xff, 0x47, 0xe0,
	0x8c, 0x3e, 0x0a, 0x69, 0x5a, 0x72, 0x99, 0xb0, 0x44, 0x9e, 0xec, 0x70, 0x72, 0x63, 0xb5, 0xd7,
	0xb8, 0x13, 0xaf, 0xc2, 0x9a, 0x8a, 0x31, 0xd8, 0x7d, 0xa6, 0xb6, 0xd5, 0x39, 0xbd, 0x77, 0xe4,
	0x3c, 0x22, 0x6c, 0xa8, 0x42, 0xd2, 0x51, 0x72, 0x9e, 0x5c, 0x6f, 0xe7, 0x61, 0x66, 0x17, 0xb0,
	0x17, 0x33, 0xce, 0x68, 0xe5, 0x08, 0x0f, 0x61, 0x5d, 0x3a, 0x11, 0x33, 0x3f, 0x23, 0xbb, 0x82,
	0xfd, 0x95, 0xd6, 0xaf, 0xe5, 0x27, 0xfd, 0x07, 0xba, 0x84, 0x83, 0xdf, 0xd4, 0x5f, 0xa8, 0xbb,
	0xaf, 0x04, 0x16, 0xab, 0xde, 0x10, 0x1f, 0x60, 0x33, 0x34, 0xe3, 0x31, 0x1f, 0x49, 0xf3, 0xb1,
	0x71, 0x9a, 0xce, 0xad, 0x7a, 0x3a, 0x5b, 0xc3, 0x27, 0x58, 0xc4, 0x4a, 0x3c, 0x99, 0x04, 0xa7,
	0xba, 0xe9, 0xe9, 0xfc, 0x72, 0xe0, 0x3c, 0xde, 0xbe, 0xdc, 0x88, 0xda, 0xbf, 0x75, 0x25, 0xaf,
	0xb4, 0xcc, 0x1c, 0xd9, 0xa6, 0x50, 0xa2, 0x53, 0xe4, 0xb2, 0xf0, 0xa9, 0xd5, 0x52, 0x90, 0x5a,
	0x36, 0xb5, 0xe7, 0xa2, 0xf6, 0xe5, 0x56, 0x78, 0xbb, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x00,
	0x85, 0x8e, 0xc8, 0x8a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	Goodbye(ctx context.Context, in *GoodbyeRequest, opts ...grpc.CallOption) (*GoodbyeResponse, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/greetergrpc.Greeter/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) Goodbye(ctx context.Context, in *GoodbyeRequest, opts ...grpc.CallOption) (*GoodbyeResponse, error) {
	out := new(GoodbyeResponse)
	err := c.cc.Invoke(ctx, "/greetergrpc.Greeter/Goodbye", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	Goodbye(context.Context, *GoodbyeRequest) (*GoodbyeResponse, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetergrpc.Greeter/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_Goodbye_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodbyeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Goodbye(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetergrpc.Greeter/Goodbye",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Goodbye(ctx, req.(*GoodbyeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greetergrpc.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Greeter_Hello_Handler,
		},
		{
			MethodName: "Goodbye",
			Handler:    _Greeter_Goodbye_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/greeter/greeter.proto",
}
